config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  get "tasks", to: "tasks#index", as: :tasks

  get "tasks/new", to: 'tasks#new'
  post "tasks", to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: :task

  get "tasks/:id/edit", to: 'tasks#edit', as: :task_edit
  patch "tasks/:id", to: 'tasks#update'

  delete "tasks/:id", to: 'tasks#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id].to_i)
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.create(tasks_params)

    redirect_to task_path(task.id)
  end

  def edit
    @task = Task.find(params[:id].to_i)
  end

  def update
    task = Task.find(params[:id].to_i)
    task.update(tasks_params)

    redirect_to task_path(task.id)
  end

  def destroy
    task = Task.find(params[:id].to_i)
    task.delete

    redirect_to root_path
  end

  private

  def tasks_params
    params.require(:task).permit(:title, :details, :completed, :checkbox_value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
   <%= f.label :completed %> <br />
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

<hr>
<%= link_to "Back to list", root_path %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<form>
  <% @tasks.each do |task| %>
  <input type="checkbox" name="task" value=<%=task.id %>>

  <label for="task"> <%= link_to task.title, task_path(task.id) %>
     <%= link_to "   Delete?", task_path(task.id), method: :delete %>
  </label><br>

  <% end %>
</form>

<hr>

<%= link_to "+ Add a new task", tasks_new_path %>
<hr>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<hr>
<%= link_to "Back to list", root_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %> </h1>
 <%= link_to "Edit this task!", task_edit_path(@task.id) %>
 <br>
 <%= link_to "Delete this task!", task_path(@task.id), method: :delete %>


<hr>

<%= @task.details %>
<hr>
<input type="checkbox" name="task" value=<%=@task.id %>>
<% if @task.completed %>
This task is completed<br>
<% else %>
This task is not completed<br>
<% end %>

<br>
<hr>
 <%= link_to "Back to list", root_path %>